combatmode:
  enabled: false
  time: 15
  timer-enabled: true
kickmode: true
teleport:
  mode: SAFE_LOCATION        # SAFE_LOCATION | NEAREST_SAFE | PUSH_BACK
  enforce-interval-ticks: 20 # re-check even if player doesn't move blocks (20 = 1s)
